version: '2'
services:
  db:
    image: neo4j:3.1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "none"
  logic:
    build: backend/
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - ".:/backend/code"
  frontend:
    build: frontend/
    ports:
      - "3000:3000"
    links:
      - logic
    
