// flow-typed signature: 5ee80a8df90d6b5042308afe84b0dc14
// flow-typed version: <<STUB>>/jsog_v^1.0.7/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsog/lib/JSOG' {
  declare module.exports: any;
}

declare module 'jsog/test/JSOGtest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsog/lib/JSOG.js' {
  declare module.exports: $Exports<'jsog/lib/JSOG'>;
}
declare module 'jsog/test/JSOGtest.js' {
  declare module.exports: $Exports<'jsog/test/JSOGtest'>;
}
