// flow-typed signature: 2107b8a158be98c8da4702613e59e42a
// flow-typed version: <<STUB>>/react-loading-animation_v^1.1.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loading-animation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loading-animation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loading-animation/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loading-animation/lib/index.js' {
  declare module.exports: $Exports<'react-loading-animation/lib/index'>;
}
