version: '2'
services:
  db:
    image: neo4j:3.1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "none"
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - ".:/code"
